flask_app/app/game/models.py
from app import db
from app.game.constants import STATUS_WAITING

class Game(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(25), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    mode = db.Column(db.String(16), nullable=False)
    status = db.Column(db.String(16), nullable=False, default=STATUS_WAITING)
    isHost = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return '<Game: code: {}, user_id: {}, id: {}>'.format(self.code, self.user_id, self.id)

flask_app/app/game/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class JoinGameForm(FlaskForm):
    join_code = StringField('Join Code', validators=[DataRequired()])
    submit = SubmitField('Join')

flask_app/app/game/routes.py
from secrets import token_hex
from turtle import goto
from flask import Blueprint, render_template, flash, redirect, url_for, request, make_response
from flask_login import current_user
from flask_socketio import emit, join_room, send
from app import db, socketio
from app.game.game import Game
from app.game.utils import save_game, load_game, delete_game
from app.game.models import Game as GameModel
from app.game.constants import HOT_SEATS_MODE, PVP_MODE, STATUS_ACTIVE, STATUS_FINISHED, PVAI_MODE
from app.game.fields import FIELDS
from app.game.ai import ai_move
from app.game.forms import JoinGameForm
from app.models import User

game = Blueprint('game', __name__)

@game.route('/')
def home():
    users_count = User.query.count()
    return render_template('game/home.html', users_count=users_count)

@game.route('/menu')
def menu():
    return render_template('game/menu.html')

@game.route('/hot_seats')
@game.route('/hot_seats/<code>', methods=['POST', 'GET'])
def hot_seats(code=None):
    payload = {
        'buy': bool(int(request.form.get('buy'))) if request.form.get('buy') else None,
        'build': request.form.get('build').split(';')[0:-1] if request.form.get('build') else None
    }
    if code:
        if request.form.get('next_turn'):
            g = load_game(code)
            g.next_turn(payload)
            if g.winner:
                game_in_db = GameModel.query.filter_by(code=code).first()
                game_in_db.status = STATUS_FINISHED
                db.session.commit()
                delete_game(code)

                flash('player {} have won!!'.format(g.winner.id), 'success')
                return redirect(url_for('game.home'))
            save_game(g, code)
        else:
            g = load_game(code)
    else:
        code = token_hex(16)
        g = Game(2)
        g.next_turn(payload)
        save_game(g, code)

        game_in_db = GameModel(code=code, user_id=current_user.id, mode=HOT_SEATS_MODE, status=STATUS_ACTIVE)
        db.session.add(game_in_db)
        db.session.commit()

    return render_template('game/board/board.html', game=g, code=code)

@game.route('/field_info/<field_id>')
def field_info(field_id):
    field_id = int(field_id)
    field_data = None
    for field in FIELDS:
        if field['id'] == field_id:
            field_data = field

    if not field_data:
        return make_response('not found'), 404

    return make_response(field_data), 200

@game.route('/vs_ai')
@game.route('/vs_ai/<code>', methods=['POST', 'GET'])
def vs_ai(code=None):
    payload = {
        'buy': bool(int(request.form.get('buy'))) if request.form.get('buy') else None,
        'build': request.form.get('build').split(';')[0:-1] if request.form.get('build') else None
    }
    if code:
        if request.form.get('next_turn'):
            g = load_game(code)
            g.next_turn(payload)
            ai_payload = ai_move(g)
            g.next_turn(ai_payload)
            if g.winner:
                game_record = GameModel.query.filter_by(code=code).first()
                game_record.status = STATUS_FINISHED
                db.session.commit()
                delete_game(code)
                flash('player {} have won!!'.format(g.winner.id), 'success')
                return redirect(url_for('game.home'))
            save_game(g, code)
        else:
            g = load_game(code)
    else:
        code = token_hex(16)
        g = Game(2)
        g.next_turn(payload)
        save_game(g, code)

        game_in_db = GameModel(code=code, user_id=current_user.id, mode=PVAI_MODE, status=STATUS_ACTIVE)
        db.session.add(game_in_db)
        db.session.commit()

    return render_template('game/board/board.html', game=g, code=code)

@game.route('/init_pvp')
def init_pvp():
    code = token_hex(16)
    g = Game(2, current_user.id)
    save_game(g, code)

    game_record = GameModel(code=code, user_id=current_user.id, mode=PVP_MODE, isHost=True)
    db.session.add(game_record)
    db.session.commit()

    return redirect(url_for('game.waiting_room', code=code))

@game.route('/waiting_room/<code>', methods=['POST', 'GET'])
def waiting_room(code):
    if request.method == 'POST':
        partner_has_joined: bool = bool(GameModel.query.filter_by(code=code, isHost=False).first())
        print(partner_has_joined)
        if partner_has_joined:
            game_record = GameModel.query.filter_by(code=code, isHost=True).first()
            game_record.status = STATUS_ACTIVE
            db.session.commit()
            return redirect(url_for('game.play_pvp', code=code))
        else:
            flash('You can not start the game, no player has joined.', 'danger')

    return render_template('game/waiting_room.html', code=code, is_host=True)

@game.route('/join_game', methods=['POST', 'GET'])
def join_game():
    form = JoinGameForm()
    if form.validate_on_submit():
        code = form.join_code.data
        game_records_count = GameModel.query.filter_by(code=code).count()
        if game_records_count == 1:
            g = load_game(code)
            g.pvp_add_joining_player(current_user.id)
            save_game(g, code)

            new_game_record = GameModel(code=code, user_id=current_user.id, mode=PVP_MODE)
            db.session.add(new_game_record)
            db.session.commit()
            return redirect(url_for('game.guest_waiting_room', code=code))
        else:
            flash('you can not join this game.', 'danger')

    return render_template('game/join_game.html', form=form)

@game.route('/guest_waiting_room/<code>', methods=['POST', 'GET'])
def guest_waiting_room(code):
    if request.method == 'POST':
        game_record = GameModel.query.filter_by(code=code, isHost=True).first()
        if game_record.status == STATUS_ACTIVE:
            return redirect(url_for('game.play_pvp', code=code))

    flash('now, wait for host to start the game.', 'primary')
    return render_template('game/waiting_room.html', is_host=False)

@game.route('/play_pvp/<code>', methods=['POST', 'GET'])
def play_pvp(code):
    payload = {
        'buy': bool(int(request.form.get('buy'))) if request.form.get('buy') else None,
        'build': request.form.get('build').split(';')[0:-1] if request.form.get('build') else None
    }
    g = load_game(code)
    if g.winner:
        socketio.emit('gameover', data={'msg': '{} won.'.format('You have' if current_user.id == g.winner.db_id else 'Enemy has')})
        flash('{} won.'.format('Enemy has' if current_user.id == g.winner.db_id else 'You have'))
        return redirect(url_for('game.home'))
    if request.form.get('next_turn'):
        last_player = g.players[g.current_player_index].db_id
        g.next_turn(payload)
        if g.winner:
            save_game(g, code)
            game_record = GameModel.query.filter_by(code=code, isHost=True)
            game_record.status = STATUS_FINISHED
            db.session.commit()
            socketio.emit('gameover', data={'msg': '{} won.'.format('You have' if current_user.id == g.winner.db_id else 'Enemy has')})
            flash('{} won.'.format('Enemy has' if current_user.id == g.winner.db_id else 'You have'))
            return redirect(url_for('game.home'))
        save_game(g, code)
        socketio.emit('refresh', data={'last_player': last_player}, broadcast=True)

    is_active = current_user.id == g.players[g.current_player_index].db_id

    return render_template(
        'game/board/board.html',
        game=g, code=code,
        pvp=True,
        is_active=is_active
        )

@socketio.on('join')
def on_join(data):
    room = data['room']
    join_room(room)

    send('', room=room)

flask_app/app/templates/game/home.html
{% extends 'layout.html' %} 

{% block css%}
    {% assets "home_scss" %}
    <link rel=stylesheet type=text/css href="{{ ASSET_URL }}">
    {% endassets %}
{% endblock %}

{% block body %}
  <div class="container">
    <div class="row">
        <div class="img-container">
            <img class="img-fluid" src="{{url_for('static', filename='images/landing.svg')}}" alt="people playing monopoly">
        </div>
        <div class="text-container">
            <h1 class="gradient-text">Investor's game</h1>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod quibusdam rerum aliquid molestiae, laboriosam laborum. Nesciunt, dicta unde nihil corrupti, accusantium numquam illo beatae praesentium facilis, sit iste aut ipsam.</p>
            <div class="att-container">
                <div class="users_count">
                    <img src="{{url_for('static', filename='images/users-solid.svg')}}" alt="people">
                    <span>
                        {%if users_count >= 100 %}
                            100+
                        {%else%}
                            {{users_count}}
                        {%endif%}
                    </span>
                    <div>registered players</div>
                </div>
                <div>
                    <button class="start-btn">
                        Are you ready?
                        <div class="icon-box">
                            <img src="{{url_for('static', filename='images/play-solid.svg')}}" alt="play icon">
                        </div>                        
                    </button>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

flask_app/app/templates/game/join_game.html
{% extends 'layout.html' %}

{% block css%}
    {% assets "join_scss" %}
    <link rel=stylesheet type=text/css href="{{ ASSET_URL }}">
    {% endassets %}
{% endblock %}

{% block body %}
    <div class="container">
        <form method="POST">
                    {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.join_code.label(class='form-control-label') }}
                            {% if form.join_code.errors %}
                                {{ form.join_code(class='form-control form-control-lg is-invalid') }}
                                <div class="invalid-feedback">
                                    {% for error in form.join_code.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.join_code(class='form-control form-control-lg') }}
                            {% endif %}
                        </div>
                    <div class="form-group">
                        {{ form.submit(class='btn') }}
                    </div>
                </form>
    </div>

{% endblock %}
 

flask_app/app/templates/game/menu.html
{% extends 'layout.html' %}

{% block css%}
    {% assets "menu_scss" %}
    <link rel=stylesheet type=text/css href="{{ ASSET_URL }}">
    {% endassets %}
{% endblock %}

{% block body %}
    <div class="container">
        <h2>choose game mode</h2>
            <div class="modes-container">
                <a class="tile" href="{{ url_for('game.hot_seats') }}">
                    <img src="{{url_for('static', filename='images/user-group-solid.svg')}}" alt="people">
                    <p>hot seats</p>
                </a>
                <a class="tile" href="{{ url_for('game.vs_ai') }}">
                    <img src="{{url_for('static', filename='images/robot-solid.svg')}}" alt="people">
                    <p>vs computer</p>
                </a>
                <a class="tile" href="{{ url_for('game.init_pvp') }}">
                    <img src="{{url_for('static', filename='images/globe-solid.svg')}}" alt="people">
                    <p>hot seats</p>
                </a>
            </div>
    </div>
{% endblock %}

flask_app/app/templates/game/waiting_room.html
{% extends 'layout.html' %}

{% block css%}
{% assets "waiting_room_scss" %}
<link rel=stylesheet type=text/css href="{{ ASSET_URL }}">
{% endassets %}
{% endblock %}

{% block body %}
<div class="container">
    <div class="content">
        {% if is_host %}
        <p>join code - send this to person you want to play with</p>
        <h2>
            <span class="code">{{ code }}</span>
            <img class="copy-icon" src="{{url_for('static', filename='images/copy-solid.svg')}}" alt="copy">
        </h2>
        <form method="POST">
            <!-- <input type="submit" value="start game" class="start-btn"> -->
            <button type="submit" class="start-btn">start game
                <div class="icon-box">
                    <img src="{{url_for('static', filename='images/play-solid.svg')}}" alt="play icon">
                </div>
            </button>
        </form>
        {% else %}
        <form method="POST">
            <input type="submit" value="play" class="btn btn-primary">
        </form>
        {% endif %}
    </div>
</div>
<script>
    document.querySelector('.copy-icon').addEventListener('click', e => {
        const code = document.querySelector('.code').textContent;
        navigator.clipboard.writeText(code);
    })
</script>
{% endblock %}